version: "3.9"
services:
    postgresql:
        image: postgres:12-alpine
        environment:
            POSTGRES_DB: axelor-open-suite
            POSTGRES_USER: axelor
            POSTGRES_PASSWORD: axelor
            POSTGRES_HOST_AUTH_METHOD: password
        restart: unless-stopped
        ports:
            - 5432:5432
